apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgAU7qINHM15hecGEGN7D0Aqjx5jkhn/YhTs59o2v1iqMhzEAMgkD8plNiwZcaWGf3VvjbmwpHnd0WdDeL/a2uKJNJcYZTeWDh/C7Hja4YowMN+Vhyg8Lj/QHva2hW/9Mzlu/8QIzEAPZvO7UXB0h5K3NvrYxQaOmJK05qtARXNQBKmxszj9AX67SFse8XMGNVPIBJWl0OCBC8h6rfuPn7GsyD069SGaxXuvPH6SgQMzlr3AxUsOHXWAMQuHeThQWPmfbCDdZZ/64SkTTORLA3HAWqOycDeYJv+/0HkgaMmf0X4TNUBlkc9vWJqQeYA5WNH8aR4tk1dnOPiNCb44mtCFWn0JECOuezBPq73wdhjWiF6nl554mUOk2HsPMngN8CwKFEtMpuQxLrk1HyEefyzzLym8Q3bWSAtelyZjVZrw/183KH9c5yoi3iLygPXK4IvPVCY5uVaQPkTuOeLDaBZMUV8ePlZVHsjkvuxNgB9iz7KZJz1KHCPlDlJn7iFSHCNl0Xe7DEVD6EVbVIxCj6o+vPwq9GqKgaNp35uEcAoETgsrdz7pORzQWa46PKvU4t0oB4fOYRZ54jfG1GBV4V1CQpKMTLWiNiuj5lgBiFczgx4fI+Z/8w8KokkSlRax8hF4un/q83oi9lbOv+wfjJO1VZCkcy3kUgmv3zbuC21mZ6KlAPmnYaIkosAeyf9DDpJJKMC+C/QK/dqCocw6pi0UXQ/KITBnQElcbMgbXWjDv1aB2EAb54WxfeZS5otD39bImVXf+94xQJKiggrgYW7Eow7uDDLLnT0XdEdB6FcabU5mDJZtWgqx5IVg+wv03b44LD373OETvOWtMjF17INzatchakk19lHehZf8ZpI/YmfZvDXJgomOUjk0N8PuCL/O+Ml4ueIQNlkbOAccrD2Z8MflE6Rc9aSBeBZIQ/0lNHPpks8NGls2DG0/Ijo23oA=
    IBM_ENTITLED_REGISTRY_USER: AgBc0PLj9tmkM7thiIceomcC5hYzpKOymJAQOX5760Jjo4HTt8wPH8GKXJ3omwjsiSLjPUidSpCT775O+2K7+6QV3VsXhkNWXJWCLfIWRegLbkbI6avCpEsVpfz46KQ/EBSD4u0KPM/AQf7l6C2V5g2fuxX8Gf9vSgYcRX0sXYVOieXyvSjMRJ1c0j6SSBSci8Nb1jpqTKxC3aJTsncwZ88qIm9u10OjNMhzgcgq2KRtfymUp5LVnpS2EEoN5wO+xXkRxjr5UCjW/Otf7CwJZMl9tqvf4DD9nziseqofS/DHZIqeHPQKuCdejvXRLNzcuuF7ESPW2qfQiXoSlL5SskFnwB40M32gYsYYyIXchzn4S24nm2mZsdABdUCzRGylts69XXOO10eeRn0szGjtf7NwA1N15kBNOKONv/ZqTO4uHHLJOxcXHKBguDXMoa+E8mnzv32gAiuMvUfldvgd5kxGUy0omOrkVpv695wGKlVjUhtv0mAx3AbhSCe8dEoXlz6I3cSM+p2+kFgWF6gzmMPeppq3aRMxJNYDLmxrBPiUmBu49+q/6krax+bxb/2hskEwP2vpSzTVRA+YNB+RYC5hJEgEabHqZCaqQMTGFKKhAv9aIFflqR7TLrX0ByeZxWtl6x4m9k0M1nv9EqFAHa6WA7Cg7jrMeZb0wwlatJGZ2EMALnxSCp2m1CSkrdB3TMWUAw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

