apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: wakefern-mf-test
  owner: wakefern-mf-test
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/wakefern-mf-test/multi-tenancy-gitops-apps.git
